### ISSUE TITLE
Rule System for command definitions

### ISSUE THREAD

**Issue by PhilippHeuer** [EnvCLI/EnvCLI#5]
# Description

Add a simple regex rule system to a command definition, for example to look for `npm start` and auto publish port 4200 as a result.

The intend is, to allow users that use containerized images that expose services to access them, without specified the exposed port in every single command again.

Therefore it should be possible to add such rules to every single command definition. (`commands:` section in the `.envcli.yml`.

# Tasks
- Modify the config file to support regex rules and `actions` list (each regex rule can have multiple actions)
- In the run command: if regex rules are defined check them and execute the actions before passing the command to docker (modify exposed ports/...)
- Add support for the `exposePort` action (can mb. later extended with other actions such as addEnvironmentVariable, or others)

# Examples
- If the command contains `npm start`, then expose port 3000 of the container on the host
- If the command contains `huge serve -p 80`, then expose the specified port on the host (thats why regex is needed for the port capture group)

# Config Sample
```yml
images:
- name: npm
  description: Node.js is a JavaScript-based platform for server-side and networking applications.
  provides:
  - npm
  - yarn
  image: docker.io/node:10-alpine
  cache:
  - name: node-10
    directory: /root/.npm
  rules:
  - regex: ".*start.*"
    actions:
    - type: exposePort
      target: 3000
    - type: addEnvironmentVariable
      target: "PORT=3000"
```
